version: '3'
services:
  execution:
    depends_on:
      - installer
  installer:
    container_name: npm_install_container
    build: .
    volumes:
      - ./:/usr/src/app
    command: "npm install"