version: '3'
services:
  app:
    container_name: node_install_container
    build: .
    volumes:
      - ./:/usr/src/app
    command: "npm install"
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost"]
    #   timeout: 2s
    #   interval: 2s
    #   retries: 10
    environment:
      - NODE_ENV=development
  execapp:
    depends_on:
      - app
      # app:
      #   condition: service_healthy