version: '3'
services:
  execution:
    container_name: execution_container
    build:  
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    command: "npm run dev"
