version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
    command: bash -c "npm config set fund false && npm install && npm run dev"
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
